# Generated by Django 5.1.7 on 2025-03-24 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="min_group",
            field=models.PositiveIntegerField(
                choices=[(10, "große Gruppe"), (5, "kleine Gruppe"), (0, "kein Limit")],
                default=0,
            ),
        ),
    ]
