# Generated by Django 5.1.7 on 2025-03-27 13:03

import django.core.validators
import events.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_date_event_min_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                validators=[
                    functools.partial(events.validators.datetime_in_future, *(2,), **{})
                ]
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
